### ISSUE TITLE
Дизайн приложения

### ISSUE THREAD

**Issue by kazachkovaanna** [kazachkovaanna/proectingGUI#2]
Требуется создать дизайн приложения.
Для этого необходимо решить, какие элементы присутствуют на каждой сцене, определить их взаимное расположение, размер. Не включается оформление: фон, шрифт, цвета элементов.
Отчетность - fxml-файлы с описанием каждой сцены

**Comment by stupid58fly** [comment]
Созданы соответствующие fxml файлы. Не добавлены элементы управления, которые должны создаваться программным путем.
