### ISSUE TITLE
Класс Maze

### ISSUE THREAD

**Issue by kazachkovaanna** [kazachkovaanna/proectingGUI#4]
Необходимо реализовать структуру данных внутри класса Maze, которая бы хранила в себе лабиринт.
Результат работы - класс, хранящий лабиринт и его описание. 
Описание должно включать:
- описание структуры данных
- объяснение, почему выбрана именно реализованная структура
- ограничения, накладываемые на лабиринт реализованной структурой

**Comment by kseniadiogenova** [comment]
Был написан класс Maze.
Структура данных: двумерный массив булевский.
